In [1]:
import random
import csv

patiala_lat = 30.3398
patiala_lon = 76.3869

num_samples = 1000 
accident_locations = []
ambulance_locations = []

for i in range(num_samples):

    lat_offset = random.uniform(-0.05, 0.05)
    lon_offset = random.uniform(-0.05, 0.05)
    

    accident_lat = patiala_lat + lat_offset
    accident_lon = patiala_lon + lon_offset
    

    ambulance_lat_offset = random.uniform(-0.01, 0.01)
    ambulance_lon_offset = random.uniform(-0.01, 0.01)
    
    ambulance_lat = accident_lat + ambulance_lat_offset
    ambulance_lon = accident_lon + ambulance_lon_offset
    

    accident_locations.append([accident_lat, accident_lon])
    ambulance_locations.append([ambulance_lat, ambulance_lon])


with open('accident_data.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['accident_latitude', 'accident_longitude', 'ambulance_latitude', 'ambulance_longitude'])
    for i in range(num_samples):
        writer.writerow([accident_locations[i][0], accident_locations[i][1]])


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


data = pd.read_csv('accident_data.csv')


data.drop_duplicates(inplace=True)
data.dropna(inplace=True)

X = data[['accident_latitude', 'accident_longitude']]
y = data[['ambulance_latitude', 'ambulance_longitude']] 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = LinearRegression()
model.fit(X_train, y_train)


score = model.score(X_test, y_test)
print(f"Accuracy: {score*100:.2f}%")


new_accident_location = [[40.7128, -74.0060]] #
predicted_ambulance_locations = model.predict(new_accident_location)
print(f"Predicted ambulance locations: {predicted_ambulance_locations}")


Accuracy: 96.35%
Predicted ambulance locations: [[ 41.58116428 -73.74803351]]


c:\Users\Akars\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [2]:
from sklearn.cluster import KMeans
import numpy as np

data = np.genfromtxt('accident_data.csv', delimiter=',', skip_header=1)
# print(data)

kmeans = KMeans(n_clusters = 10 , random_state =0).fit(data)

Ambulance_locations = kmeans.cluster_centers_
print(Ambulance_locations)

c:\Users\Akars\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


[[30.33360812 76.37999653 30.33393642 76.38008673]
 [30.37016564 76.42118713 30.37045209 76.42140582]
 [30.30729578 76.4023385  30.30699064 76.40238999]
 [30.37585973 76.35487572 30.37711746 76.35445481]
 [30.30997837 76.34796422 30.30949029 76.34664837]
 [30.36921181 76.39098289 30.37078424 76.39100096]
 [30.30921615 76.42810321 30.30816642 76.42835038]
 [30.30441046 76.37518902 30.30285261 76.37524116]
 [30.33881708 76.4187556  30.33820864 76.42019578]
 [30.34669839 76.35301503 30.34660812 76.35117366]]
